---
server: irc.example.net
nick: dart
channels:
  - "#dart"
owner: ".*!(?:wheaties|monty)@127.0.0.1"

commands:
  # Causes Dart to disconnect and exit.
  quit:
    do: Thread.main.exit
  
  # Standard /bin/echo.
  echo: &echo
    do: privmsg `echo "#{args.join(' ')}"`, source
  say: *echo
  
  # Downloads a file to ~/Downloads.
  dl:
    do: |
      `wget -q -P ~/Downloads #{args.first}`
      privmsg "Finished downloading #{args.first}!", source
